export interface SeedInvestor {
  name: string;
  slug: string;
  type:
    | "vc_firm"
    | "angel"
    | "corporate_vc"
    | "accelerator"
    | "pe_firm"
    | "sovereign_fund"
    | "family_office"
    | "hedge_fund";
  website: string;
  description: string;
  hq_city: string;
  hq_country: string;
  founded_year: number | null;
  focus_areas: string[];
  linkedin_url: string | null;
}

export const seedInvestors: SeedInvestor[] = [
  {
    name: "Sequoia Capital",
    slug: "sequoia-capital",
    type: "vc_firm",
    website: "https://sequoiacap.com",
    description: "Storied venture firm investing across stages, with deep AI and infrastructure exposure.",
    hq_city: "Menlo Park",
    hq_country: "USA",
    founded_year: 1972,
    focus_areas: ["AI Infra", "Foundation Models", "Enterprise AI"],
    linkedin_url: "https://linkedin.com/company/sequoia-capital",
  },
  {
    name: "Andreessen Horowitz",
    slug: "andreessen-horowitz",
    type: "vc_firm",
    website: "https://a16z.com",
    description: "Large multi-stage VC firm with a dedicated AI investment practice (a16z AI).",
    hq_city: "Menlo Park",
    hq_country: "USA",
    founded_year: 2009,
    focus_areas: ["AI Infra", "Consumer AI", "Crypto"],
    linkedin_url: "https://linkedin.com/company/andreessen-horowitz",
  },
  {
    name: "Thrive Capital",
    slug: "thrive-capital",
    type: "vc_firm",
    website: "https://thrivecap.com",
    description: "Growth-stage investment firm known for concentrated bets in leading AI labs.",
    hq_city: "New York",
    hq_country: "USA",
    founded_year: 2009,
    focus_areas: ["Foundation Models", "Growth"],
    linkedin_url: "https://linkedin.com/company/thrive-capital",
  },
  {
    name: "Founders Fund",
    slug: "founders-fund",
    type: "vc_firm",
    website: "https://foundersfund.com",
    description: "Venture firm backing contrarian and deep-tech bets including AI and robotics.",
    hq_city: "San Francisco",
    hq_country: "USA",
    founded_year: 2005,
    focus_areas: ["AI Infra", "Robotics", "Deep Tech"],
    linkedin_url: "https://linkedin.com/company/founders-fund",
  },
  {
    name: "Khosla Ventures",
    slug: "khosla-ventures",
    type: "vc_firm",
    website: "https://khoslaventures.com",
    description: "Early-stage VC with a long history of high-conviction AI and frontier tech investments.",
    hq_city: "Menlo Park",
    hq_country: "USA",
    founded_year: 2004,
    focus_areas: ["AI Infra", "Frontier Tech", "Climate"],
    linkedin_url: "https://linkedin.com/company/khosla-ventures",
  },
  {
    name: "Coatue Management",
    slug: "coatue-management",
    type: "hedge_fund",
    website: "https://coatue.com",
    description: "Technology-focused investment firm participating in growth and crossover AI rounds.",
    hq_city: "New York",
    hq_country: "USA",
    founded_year: 1999,
    focus_areas: ["Growth", "Foundation Models"],
    linkedin_url: "https://linkedin.com/company/coatue-management",
  },
  {
    name: "Tiger Global Management",
    slug: "tiger-global",
    type: "hedge_fund",
    website: "https://tigerglobal.com",
    description: "Global investment firm active in growth-stage technology and AI financings.",
    hq_city: "New York",
    hq_country: "USA",
    founded_year: 2001,
    focus_areas: ["Growth", "Enterprise AI"],
    linkedin_url: "https://linkedin.com/company/tiger-global-management",
  },
  {
    name: "Microsoft",
    slug: "microsoft",
    type: "corporate_vc",
    website: "https://microsoft.com",
    description: "Strategic corporate investor and cloud partner across multiple leading AI labs.",
    hq_city: "Redmond",
    hq_country: "USA",
    founded_year: 1975,
    focus_areas: ["Foundation Models", "Cloud AI"],
    linkedin_url: "https://linkedin.com/company/microsoft",
  },
  {
    name: "NVIDIA",
    slug: "nvidia",
    type: "corporate_vc",
    website: "https://nvidia.com",
    description: "Strategic investor across the AI compute and application stack via NVentures.",
    hq_city: "Santa Clara",
    hq_country: "USA",
    founded_year: 1993,
    focus_areas: ["Compute", "Foundation Models", "Robotics"],
    linkedin_url: "https://linkedin.com/company/nvidia",
  },
  {
    name: "Amazon",
    slug: "amazon",
    type: "corporate_vc",
    website: "https://amazon.com",
    description: "Strategic investor and cloud partner for AI labs via AWS and corporate development.",
    hq_city: "Seattle",
    hq_country: "USA",
    founded_year: 1994,
    focus_areas: ["Foundation Models", "Cloud AI"],
    linkedin_url: "https://linkedin.com/company/amazon",
  },
  {
    name: "Salesforce Ventures",
    slug: "salesforce-ventures",
    type: "corporate_vc",
    website: "https://salesforceventures.com",
    description: "Corporate venture arm investing in enterprise AI and SaaS companies.",
    hq_city: "San Francisco",
    hq_country: "USA",
    founded_year: 2009,
    focus_areas: ["Enterprise AI", "SaaS"],
    linkedin_url: "https://linkedin.com/company/salesforce-ventures",
  },
  {
    name: "Lightspeed Venture Partners",
    slug: "lightspeed-venture-partners",
    type: "vc_firm",
    website: "https://lsvp.com",
    description: "Multi-stage VC firm with significant investments across the AI infrastructure stack.",
    hq_city: "Menlo Park",
    hq_country: "USA",
    founded_year: 2000,
    focus_areas: ["AI Infra", "Enterprise AI"],
    linkedin_url: "https://linkedin.com/company/lightspeed-venture-partners",
  },
  {
    name: "Index Ventures",
    slug: "index-ventures",
    type: "vc_firm",
    website: "https://indexventures.com",
    description: "Transatlantic VC firm active in both US and European AI investments.",
    hq_city: "San Francisco",
    hq_country: "USA",
    founded_year: 1996,
    focus_areas: ["Developer Tools", "Enterprise AI", "European AI"],
    linkedin_url: "https://linkedin.com/company/index-ventures",
  },
  {
    name: "Accel",
    slug: "accel",
    type: "vc_firm",
    website: "https://accel.com",
    description: "Global venture firm with early bets across AI infrastructure and applications.",
    hq_city: "Palo Alto",
    hq_country: "USA",
    founded_year: 1983,
    focus_areas: ["AI Infra", "Enterprise AI"],
    linkedin_url: "https://linkedin.com/company/accel",
  },
  {
    name: "Greenoaks Capital",
    slug: "greenoaks-capital",
    type: "vc_firm",
    website: "https://greenoaks.com",
    description: "Concentrated growth investor known for large checks in category-leading AI companies.",
    hq_city: "San Francisco",
    hq_country: "USA",
    founded_year: 2012,
    focus_areas: ["Growth", "Foundation Models"],
    linkedin_url: null,
  },
  {
    name: "General Catalyst",
    slug: "general-catalyst",
    type: "vc_firm",
    website: "https://generalcatalyst.com",
    description: "Multi-stage VC firm investing across AI infrastructure, healthcare AI, and fintech.",
    hq_city: "San Francisco",
    hq_country: "USA",
    founded_year: 2000,
    focus_areas: ["AI Infra", "Healthcare AI", "Fintech"],
    linkedin_url: "https://linkedin.com/company/general-catalyst",
  },
  {
    name: "ICONIQ Growth",
    slug: "iconiq-growth",
    type: "vc_firm",
    website: "https://iconiqcapital.com",
    description: "Growth equity firm backing late-stage technology and AI companies.",
    hq_city: "San Francisco",
    hq_country: "USA",
    founded_year: 2011,
    focus_areas: ["Growth", "Enterprise AI"],
    linkedin_url: "https://linkedin.com/company/iconiq-capital",
  },
  {
    name: "Y Combinator",
    slug: "y-combinator",
    type: "accelerator",
    website: "https://ycombinator.com",
    description: "Leading early-stage accelerator and seed investor across hundreds of AI startups.",
    hq_city: "San Francisco",
    hq_country: "USA",
    founded_year: 2005,
    focus_areas: ["Seed", "All Sectors"],
    linkedin_url: "https://linkedin.com/company/y-combinator",
  },
  {
    name: "Conviction",
    slug: "conviction",
    type: "vc_firm",
    website: "https://conviction.com",
    description: "AI-focused venture firm founded by Sarah Guo, investing primarily at seed and Series A.",
    hq_city: "San Francisco",
    hq_country: "USA",
    founded_year: 2022,
    focus_areas: ["AI Infra", "Agents", "Applied AI"],
    linkedin_url: null,
  },
  {
    name: "Radical Ventures",
    slug: "radical-ventures",
    type: "vc_firm",
    website: "https://radical.vc",
    description: "AI-focused venture firm investing globally across AI infrastructure and applications.",
    hq_city: "Toronto",
    hq_country: "Canada",
    founded_year: 2018,
    focus_areas: ["AI Infra", "Applied AI"],
    linkedin_url: "https://linkedin.com/company/radical-ventures",
  },
  {
    name: "Bond Capital",
    slug: "bond-capital",
    type: "vc_firm",
    website: "https://bondcap.com",
    description: "Growth-stage investment firm backing category leaders across consumer and enterprise AI.",
    hq_city: "San Francisco",
    hq_country: "USA",
    founded_year: 2018,
    focus_areas: ["Growth", "Consumer AI"],
    linkedin_url: null,
  },
];
