// Hand-curated seed data — realistic AI company profiles for demo purposes.
// Numbers are illustrative approximations for prototype purposes, not live financial data.

export interface SeedCompany {
  name: string;
  slug: string;
  website: string;
  one_liner: string;
  description: string;
  founded_year: number;
  hq_city: string;
  hq_country: string;
  stage:
    | "idea"
    | "pre_seed"
    | "seed"
    | "series_a"
    | "series_b"
    | "series_c"
    | "series_d_plus"
    | "growth"
    | "public"
    | "acquired"
    | "shut_down";
  employee_range: string;
  categories: string[];
  tags: string[];
  is_unicorn: boolean;
  valuation_usd: number | null;
  status: "active" | "acquired" | "shut_down";
  linkedin_url: string | null;
}

export const seedCompanies: SeedCompany[] = [
  {
    name: "OpenAI",
    slug: "openai",
    website: "https://openai.com",
    one_liner: "Frontier AI research lab and developer of the GPT model family.",
    description:
      "OpenAI develops large language models and AI products including ChatGPT, GPT-4/5, and the OpenAI API, with a mission focused on safe and broadly beneficial AGI.",
    founded_year: 2015,
    hq_city: "San Francisco",
    hq_country: "USA",
    stage: "growth",
    employee_range: "1000+",
    categories: ["LLM", "Foundation Models", "Consumer AI"],
    tags: ["AGI", "ChatGPT", "API"],
    is_unicorn: true,
    valuation_usd: 157000000000,
    status: "active",
    linkedin_url: "https://linkedin.com/company/openai",
  },
  {
    name: "Anthropic",
    slug: "anthropic",
    website: "https://anthropic.com",
    one_liner: "AI safety company building the Claude family of models.",
    description:
      "Anthropic is an AI safety and research company that builds reliable, interpretable, and steerable AI systems, including the Claude model family.",
    founded_year: 2021,
    hq_city: "San Francisco",
    hq_country: "USA",
    stage: "growth",
    employee_range: "1000+",
    categories: ["LLM", "Foundation Models", "AI Safety"],
    tags: ["Claude", "Constitutional AI", "API"],
    is_unicorn: true,
    valuation_usd: 61500000000,
    status: "active",
    linkedin_url: "https://linkedin.com/company/anthropicresearch",
  },
  {
    name: "Mistral AI",
    slug: "mistral-ai",
    website: "https://mistral.ai",
    one_liner: "European open-weight foundation model company.",
    description:
      "Mistral AI builds open and commercial large language models, positioning itself as Europe's leading sovereign AI lab.",
    founded_year: 2023,
    hq_city: "Paris",
    hq_country: "France",
    stage: "series_b",
    employee_range: "201-500",
    categories: ["LLM", "Open Source", "Foundation Models"],
    tags: ["open-weight", "European AI"],
    is_unicorn: true,
    valuation_usd: 6200000000,
    status: "active",
    linkedin_url: "https://linkedin.com/company/mistralai",
  },
  {
    name: "Cohere",
    slug: "cohere",
    website: "https://cohere.com",
    one_liner: "Enterprise-focused LLM platform.",
    description:
      "Cohere provides large language models and retrieval tooling built specifically for enterprise deployment and security requirements.",
    founded_year: 2019,
    hq_city: "Toronto",
    hq_country: "Canada",
    stage: "series_d_plus",
    employee_range: "501-1000",
    categories: ["LLM", "Enterprise AI"],
    tags: ["RAG", "enterprise"],
    is_unicorn: true,
    valuation_usd: 5500000000,
    status: "active",
    linkedin_url: "https://linkedin.com/company/cohere-ai",
  },
  {
    name: "Perplexity",
    slug: "perplexity",
    website: "https://perplexity.ai",
    one_liner: "AI-native answer engine and search assistant.",
    description:
      "Perplexity builds an AI-powered search and research assistant that synthesizes cited answers from real-time web data.",
    founded_year: 2022,
    hq_city: "San Francisco",
    hq_country: "USA",
    stage: "series_d_plus",
    employee_range: "51-200",
    categories: ["Search", "Consumer AI", "Agents"],
    tags: ["answer engine", "RAG"],
    is_unicorn: true,
    valuation_usd: 18000000000,
    status: "active",
    linkedin_url: "https://linkedin.com/company/perplexity-ai",
  },
  {
    name: "Hugging Face",
    slug: "hugging-face",
    website: "https://huggingface.co",
    one_liner: "Open platform and hub for ML models, datasets, and tools.",
    description:
      "Hugging Face hosts the largest open repository of ML models and datasets and builds open-source tooling (Transformers, Diffusers) used across the industry.",
    founded_year: 2016,
    hq_city: "New York",
    hq_country: "USA",
    stage: "series_d_plus",
    employee_range: "201-500",
    categories: ["Developer Tools", "Open Source", "MLOps"],
    tags: ["model hub", "transformers"],
    is_unicorn: true,
    valuation_usd: 4500000000,
    status: "active",
    linkedin_url: "https://linkedin.com/company/huggingface",
  },
  {
    name: "Scale AI",
    slug: "scale-ai",
    website: "https://scale.com",
    one_liner: "Data labeling and evaluation infrastructure for AI models.",
    description:
      "Scale AI provides data annotation, RLHF, and evaluation infrastructure that powers training pipelines for leading AI labs and enterprises.",
    founded_year: 2016,
    hq_city: "San Francisco",
    hq_country: "USA",
    stage: "growth",
    employee_range: "501-1000",
    categories: ["Data Infra", "MLOps", "RLHF"],
    tags: ["data labeling", "evaluation"],
    is_unicorn: true,
    valuation_usd: 13800000000,
    status: "active",
    linkedin_url: "https://linkedin.com/company/scaleai",
  },
  {
    name: "Together AI",
    slug: "together-ai",
    website: "https://together.ai",
    one_liner: "Cloud platform for training and running open-source AI models.",
    description:
      "Together AI provides GPU cloud infrastructure and inference APIs optimized for open-source foundation models.",
    founded_year: 2022,
    hq_city: "San Francisco",
    hq_country: "USA",
    stage: "series_b",
    employee_range: "51-200",
    categories: ["Infra", "Compute", "Inference"],
    tags: ["GPU cloud", "open-source models"],
    is_unicorn: true,
    valuation_usd: 3300000000,
    status: "active",
    linkedin_url: "https://linkedin.com/company/together-ai",
  },
  {
    name: "Groq",
    slug: "groq",
    website: "https://groq.com",
    one_liner: "Custom silicon (LPU) for ultra-fast LLM inference.",
    description:
      "Groq designs custom Language Processing Unit (LPU) chips built specifically for low-latency, high-throughput LLM inference.",
    founded_year: 2016,
    hq_city: "Mountain View",
    hq_country: "USA",
    stage: "series_d_plus",
    employee_range: "201-500",
    categories: ["Hardware", "Inference", "Chips"],
    tags: ["LPU", "silicon"],
    is_unicorn: true,
    valuation_usd: 6900000000,
    status: "active",
    linkedin_url: "https://linkedin.com/company/groq",
  },
  {
    name: "Runway",
    slug: "runway",
    website: "https://runwayml.com",
    one_liner: "Generative video and creative-tools AI platform.",
    description:
      "Runway builds generative AI models and tools for video, image, and creative content generation aimed at filmmakers and creators.",
    founded_year: 2018,
    hq_city: "New York",
    hq_country: "USA",
    stage: "series_d_plus",
    employee_range: "201-500",
    categories: ["Generative Video", "Creative AI"],
    tags: ["video generation", "Gen-3"],
    is_unicorn: true,
    valuation_usd: 3000000000,
    status: "active",
    linkedin_url: "https://linkedin.com/company/runwayml",
  },
  {
    name: "Midjourney",
    slug: "midjourney",
    website: "https://midjourney.com",
    one_liner: "Text-to-image generative AI lab.",
    description:
      "Midjourney is an independent research lab producing one of the most widely used text-to-image generative AI tools, run as a self-funded, profitable company.",
    founded_year: 2021,
    hq_city: "San Francisco",
    hq_country: "USA",
    stage: "growth",
    employee_range: "11-50",
    categories: ["Generative Image", "Consumer AI"],
    tags: ["text-to-image", "bootstrapped"],
    is_unicorn: false,
    valuation_usd: null,
    status: "active",
    linkedin_url: null,
  },
  {
    name: "Character.AI",
    slug: "character-ai",
    website: "https://character.ai",
    one_liner: "Platform for creating and chatting with AI personas.",
    description:
      "Character.AI lets users create and interact with customizable AI characters and personas across entertainment, companionship, and roleplay use cases.",
    founded_year: 2021,
    hq_city: "Menlo Park",
    hq_country: "USA",
    stage: "series_b",
    employee_range: "51-200",
    categories: ["Consumer AI", "Chatbots", "Entertainment"],
    tags: ["personas", "chat"],
    is_unicorn: true,
    valuation_usd: 1000000000,
    status: "active",
    linkedin_url: "https://linkedin.com/company/characterai",
  },
  {
    name: "Glean",
    slug: "glean",
    website: "https://glean.com",
    one_liner: "Enterprise AI search and knowledge assistant.",
    description:
      "Glean builds an enterprise AI search and work assistant that connects across internal company tools to surface knowledge and automate workflows.",
    founded_year: 2019,
    hq_city: "Palo Alto",
    hq_country: "USA",
    stage: "series_d_plus",
    employee_range: "201-500",
    categories: ["Enterprise AI", "Search", "Productivity"],
    tags: ["work assistant", "RAG"],
    is_unicorn: true,
    valuation_usd: 7200000000,
    status: "active",
    linkedin_url: "https://linkedin.com/company/glean-work",
  },
  {
    name: "Harvey",
    slug: "harvey",
    website: "https://harvey.ai",
    one_liner: "AI platform purpose-built for legal professionals.",
    description:
      "Harvey provides generative AI tools tailored for law firms and legal departments, covering research, drafting, and document review workflows.",
    founded_year: 2022,
    hq_city: "San Francisco",
    hq_country: "USA",
    stage: "series_d_plus",
    employee_range: "201-500",
    categories: ["Legal Tech", "Vertical AI", "Enterprise AI"],
    tags: ["legal AI", "document review"],
    is_unicorn: true,
    valuation_usd: 5000000000,
    status: "active",
    linkedin_url: "https://linkedin.com/company/harvey-ai",
  },
  {
    name: "Sierra",
    slug: "sierra",
    website: "https://sierra.ai",
    one_liner: "AI customer-experience agent platform.",
    description:
      "Sierra builds conversational AI agents that handle customer service interactions on behalf of enterprise brands.",
    founded_year: 2023,
    hq_city: "San Francisco",
    hq_country: "USA",
    stage: "series_b",
    employee_range: "51-200",
    categories: ["Agents", "Customer Experience", "Enterprise AI"],
    tags: ["AI agents", "customer service"],
    is_unicorn: true,
    valuation_usd: 10000000000,
    status: "active",
    linkedin_url: "https://linkedin.com/company/sierra-platform",
  },
  {
    name: "Cursor (Anysphere)",
    slug: "cursor",
    website: "https://cursor.com",
    one_liner: "AI-native code editor built on top of VS Code.",
    description:
      "Anysphere builds Cursor, an AI-first code editor designed for fast, AI-assisted software development at scale.",
    founded_year: 2022,
    hq_city: "San Francisco",
    hq_country: "USA",
    stage: "series_b",
    employee_range: "51-200",
    categories: ["Dev Tools", "Coding Agents", "Developer Productivity"],
    tags: ["AI IDE", "code generation"],
    is_unicorn: true,
    valuation_usd: 9900000000,
    status: "active",
    linkedin_url: "https://linkedin.com/company/anysphere",
  },
  {
    name: "Replit",
    slug: "replit",
    website: "https://replit.com",
    one_liner: "Browser-based collaborative coding platform with AI agents.",
    description:
      "Replit provides a cloud development environment with built-in AI coding agents that can build and deploy full applications from natural language.",
    founded_year: 2016,
    hq_city: "San Francisco",
    hq_country: "USA",
    stage: "series_d_plus",
    employee_range: "51-200",
    categories: ["Dev Tools", "Coding Agents"],
    tags: ["cloud IDE", "AI agent"],
    is_unicorn: true,
    valuation_usd: 3000000000,
    status: "active",
    linkedin_url: "https://linkedin.com/company/repl-it",
  },
  {
    name: "Adept AI",
    slug: "adept-ai",
    website: "https://adept.ai",
    one_liner: "AI agents that operate software and complete digital tasks.",
    description:
      "Adept builds AI agents designed to interact with software interfaces directly, automating multi-step digital workflows.",
    founded_year: 2022,
    hq_city: "San Francisco",
    hq_country: "USA",
    stage: "series_b",
    employee_range: "51-200",
    categories: ["Agents", "Automation"],
    tags: ["action models", "agents"],
    is_unicorn: false,
    valuation_usd: 1000000000,
    status: "active",
    linkedin_url: "https://linkedin.com/company/adept-ai-labs",
  },
  {
    name: "Inflection AI",
    slug: "inflection-ai",
    website: "https://inflection.ai",
    one_liner: "Personal AI assistant company (Pi).",
    description:
      "Inflection AI develops personal AI systems, including the Pi assistant, focused on emotionally intelligent conversation.",
    founded_year: 2022,
    hq_city: "Palo Alto",
    hq_country: "USA",
    stage: "series_b",
    employee_range: "11-50",
    categories: ["Consumer AI", "Chatbots"],
    tags: ["personal AI", "Pi"],
    is_unicorn: true,
    valuation_usd: 4000000000,
    status: "active",
    linkedin_url: "https://linkedin.com/company/inflectionai",
  },
  {
    name: "Stability AI",
    slug: "stability-ai",
    website: "https://stability.ai",
    one_liner: "Open generative AI models, including Stable Diffusion.",
    description:
      "Stability AI develops and open-sources generative AI models across image, video, audio, and 3D modalities, including the Stable Diffusion family.",
    founded_year: 2019,
    hq_city: "London",
    hq_country: "UK",
    stage: "series_c",
    employee_range: "51-200",
    categories: ["Generative Image", "Open Source"],
    tags: ["Stable Diffusion", "open weights"],
    is_unicorn: false,
    valuation_usd: 1000000000,
    status: "active",
    linkedin_url: "https://linkedin.com/company/stabilityai",
  },
  {
    name: "ElevenLabs",
    slug: "elevenlabs",
    website: "https://elevenlabs.io",
    one_liner: "AI voice generation and cloning platform.",
    description:
      "ElevenLabs builds realistic AI voice synthesis, cloning, and dubbing technology used across media, gaming, and accessibility.",
    founded_year: 2022,
    hq_city: "London",
    hq_country: "UK",
    stage: "series_c",
    employee_range: "51-200",
    categories: ["Voice AI", "Audio", "Generative Audio"],
    tags: ["voice cloning", "TTS"],
    is_unicorn: true,
    valuation_usd: 3300000000,
    status: "active",
    linkedin_url: "https://linkedin.com/company/elevenlabsio",
  },
  {
    name: "Synthesia",
    slug: "synthesia",
    website: "https://synthesia.io",
    one_liner: "AI video generation platform with digital avatars.",
    description:
      "Synthesia provides an AI video generation platform that creates videos with realistic digital avatars from text scripts.",
    founded_year: 2017,
    hq_city: "London",
    hq_country: "UK",
    stage: "series_d_plus",
    employee_range: "201-500",
    categories: ["Generative Video", "Enterprise AI"],
    tags: ["avatars", "video generation"],
    is_unicorn: true,
    valuation_usd: 2100000000,
    status: "active",
    linkedin_url: "https://linkedin.com/company/synthesia-io",
  },
  {
    name: "Pika",
    slug: "pika",
    website: "https://pika.art",
    one_liner: "Text and image-to-video generation platform.",
    description:
      "Pika develops generative AI models that turn text and image prompts into short-form video content.",
    founded_year: 2023,
    hq_city: "Palo Alto",
    hq_country: "USA",
    stage: "series_b",
    employee_range: "11-50",
    categories: ["Generative Video", "Consumer AI"],
    tags: ["video generation"],
    is_unicorn: false,
    valuation_usd: 470000000,
    status: "active",
    linkedin_url: "https://linkedin.com/company/pika-labs",
  },
  {
    name: "Suno",
    slug: "suno",
    website: "https://suno.com",
    one_liner: "AI music generation platform.",
    description:
      "Suno builds generative AI models that create full songs—including vocals, lyrics, and instrumentation—from text prompts.",
    founded_year: 2023,
    hq_city: "Cambridge",
    hq_country: "USA",
    stage: "series_b",
    employee_range: "11-50",
    categories: ["Generative Audio", "Music", "Consumer AI"],
    tags: ["music generation"],
    is_unicorn: true,
    valuation_usd: 2450000000,
    status: "active",
    linkedin_url: "https://linkedin.com/company/suno-ai",
  },
  {
    name: "Pinecone",
    slug: "pinecone",
    website: "https://pinecone.io",
    one_liner: "Managed vector database for AI applications.",
    description:
      "Pinecone provides a fully managed vector database used for retrieval-augmented generation, semantic search, and recommendation systems.",
    founded_year: 2019,
    hq_city: "New York",
    hq_country: "USA",
    stage: "series_c",
    employee_range: "51-200",
    categories: ["Data Infra", "Vector DB", "RAG"],
    tags: ["vector search", "infrastructure"],
    is_unicorn: false,
    valuation_usd: 750000000,
    status: "active",
    linkedin_url: "https://linkedin.com/company/pinecone-io",
  },
  {
    name: "Weights & Biases",
    slug: "weights-and-biases",
    website: "https://wandb.ai",
    one_liner: "MLOps platform for experiment tracking and model evaluation.",
    description:
      "Weights & Biases provides tools for tracking ML experiments, evaluating models, and managing the ML development lifecycle.",
    founded_year: 2017,
    hq_city: "San Francisco",
    hq_country: "USA",
    stage: "series_c",
    employee_range: "201-500",
    categories: ["MLOps", "Developer Tools"],
    tags: ["experiment tracking", "evaluation"],
    is_unicorn: true,
    valuation_usd: 1250000000,
    status: "active",
    linkedin_url: "https://linkedin.com/company/wandb",
  },
  {
    name: "LangChain",
    slug: "langchain",
    website: "https://langchain.com",
    one_liner: "Framework and platform for building LLM applications.",
    description:
      "LangChain builds open-source frameworks and a commercial platform (LangSmith) for developing, debugging, and deploying LLM-powered applications.",
    founded_year: 2022,
    hq_city: "San Francisco",
    hq_country: "USA",
    stage: "series_a",
    employee_range: "11-50",
    categories: ["Developer Tools", "Agents", "Open Source"],
    tags: ["LLM framework", "LangSmith"],
    is_unicorn: false,
    valuation_usd: 1250000000,
    status: "active",
    linkedin_url: "https://linkedin.com/company/langchain",
  },
  {
    name: "Magic AI",
    slug: "magic-ai",
    website: "https://magic.dev",
    one_liner: "Long-context AI software engineer models.",
    description:
      "Magic develops large-context foundation models specialized for autonomous software engineering tasks.",
    founded_year: 2022,
    hq_city: "San Francisco",
    hq_country: "USA",
    stage: "series_b",
    employee_range: "11-50",
    categories: ["Coding Agents", "Foundation Models"],
    tags: ["long context", "code models"],
    is_unicorn: true,
    valuation_usd: 1500000000,
    status: "active",
    linkedin_url: "https://linkedin.com/company/magic-ai-dev",
  },
  {
    name: "Codeium (Windsurf)",
    slug: "codeium",
    website: "https://codeium.com",
    one_liner: "AI coding assistant and agentic IDE (Windsurf).",
    description:
      "Codeium builds the Windsurf AI-native IDE and coding assistant products used by developers for autocomplete, chat, and agentic coding workflows.",
    founded_year: 2021,
    hq_city: "Mountain View",
    hq_country: "USA",
    stage: "series_c",
    employee_range: "51-200",
    categories: ["Dev Tools", "Coding Agents"],
    tags: ["Windsurf", "autocomplete"],
    is_unicorn: true,
    valuation_usd: 1250000000,
    status: "active",
    linkedin_url: "https://linkedin.com/company/codeium",
  },
  {
    name: "Mercor",
    slug: "mercor",
    website: "https://mercor.com",
    one_liner: "AI-powered hiring and talent-matching platform.",
    description:
      "Mercor uses AI to evaluate, vet, and match technical talent with companies, and provides data/RLHF labor pipelines for AI labs.",
    founded_year: 2023,
    hq_city: "San Francisco",
    hq_country: "USA",
    stage: "series_b",
    employee_range: "51-200",
    categories: ["HR Tech", "Vertical AI", "Data Infra"],
    tags: ["hiring", "RLHF labor"],
    is_unicorn: true,
    valuation_usd: 2000000000,
    status: "active",
    linkedin_url: "https://linkedin.com/company/mercor-ai",
  },
  {
    name: "Decagon",
    slug: "decagon",
    website: "https://decagon.ai",
    one_liner: "AI customer support agent platform.",
    description:
      "Decagon builds AI agents for enterprise customer support that can resolve complex, multi-step support conversations.",
    founded_year: 2023,
    hq_city: "San Francisco",
    hq_country: "USA",
    stage: "series_c",
    employee_range: "51-200",
    categories: ["Agents", "Customer Experience"],
    tags: ["support automation"],
    is_unicorn: true,
    valuation_usd: 1500000000,
    status: "active",
    linkedin_url: "https://linkedin.com/company/decagonai",
  },
  {
    name: "Physical Intelligence",
    slug: "physical-intelligence",
    website: "https://physicalintelligence.company",
    one_liner: "Foundation models for general-purpose robotics.",
    description:
      "Physical Intelligence develops general-purpose foundation models intended to give robots broad physical and manipulation capabilities.",
    founded_year: 2024,
    hq_city: "San Francisco",
    hq_country: "USA",
    stage: "series_a",
    employee_range: "11-50",
    categories: ["Robotics", "Foundation Models"],
    tags: ["robot foundation models"],
    is_unicorn: true,
    valuation_usd: 2400000000,
    status: "active",
    linkedin_url: null,
  },
  {
    name: "Figure AI",
    slug: "figure-ai",
    website: "https://figure.ai",
    one_liner: "Humanoid robotics company.",
    description:
      "Figure designs general-purpose humanoid robots intended for commercial labor applications, paired with AI models for perception and control.",
    founded_year: 2022,
    hq_city: "Sunnyvale",
    hq_country: "USA",
    stage: "series_b",
    employee_range: "201-500",
    categories: ["Robotics", "Hardware"],
    tags: ["humanoid robots"],
    is_unicorn: true,
    valuation_usd: 39000000000,
    status: "active",
    linkedin_url: "https://linkedin.com/company/figureai",
  },
  {
    name: "Skild AI",
    slug: "skild-ai",
    website: "https://skild.ai",
    one_liner: "General-purpose 'brain' for robots across form factors.",
    description:
      "Skild AI builds a general-purpose robotics foundation model intended to work across many different robot hardware platforms.",
    founded_year: 2023,
    hq_city: "Pittsburgh",
    hq_country: "USA",
    stage: "series_a",
    employee_range: "51-200",
    categories: ["Robotics", "Foundation Models"],
    tags: ["robot brain"],
    is_unicorn: true,
    valuation_usd: 4500000000,
    status: "active",
    linkedin_url: "https://linkedin.com/company/skild-ai",
  },
  {
    name: "World Labs",
    slug: "world-labs",
    website: "https://worldlabs.ai",
    one_liner: "Spatial intelligence and 3D world models.",
    description:
      "World Labs researches large world models that give AI systems spatial understanding of 3D environments, founded by Fei-Fei Li.",
    founded_year: 2024,
    hq_city: "San Francisco",
    hq_country: "USA",
    stage: "series_a",
    employee_range: "11-50",
    categories: ["World Models", "Foundation Models", "Spatial AI"],
    tags: ["3D", "spatial intelligence"],
    is_unicorn: true,
    valuation_usd: 1000000000,
    status: "active",
    linkedin_url: null,
  },
  {
    name: "Safe Superintelligence Inc.",
    slug: "safe-superintelligence",
    website: "https://ssi.inc",
    one_liner: "Research lab focused solely on safe superintelligence.",
    description:
      "Safe Superintelligence Inc. is a research lab pursuing safe superintelligence as its sole focus, with no near-term commercial product.",
    founded_year: 2024,
    hq_city: "Palo Alto",
    hq_country: "USA",
    stage: "series_a",
    employee_range: "11-50",
    categories: ["AI Safety", "Foundation Models"],
    tags: ["superintelligence", "research lab"],
    is_unicorn: true,
    valuation_usd: 32000000000,
    status: "active",
    linkedin_url: null,
  },
  {
    name: "Thinking Machines Lab",
    slug: "thinking-machines-lab",
    website: "https://thinkingmachines.ai",
    one_liner: "AI research lab building collaborative general-purpose systems.",
    description:
      "Thinking Machines Lab is an AI research and product company focused on making AI systems more broadly understandable, customizable, and collaborative.",
    founded_year: 2025,
    hq_city: "San Francisco",
    hq_country: "USA",
    stage: "seed",
    employee_range: "11-50",
    categories: ["Foundation Models", "AI Safety"],
    tags: ["research lab"],
    is_unicorn: true,
    valuation_usd: 12000000000,
    status: "active",
    linkedin_url: null,
  },
  {
    name: "Lovable",
    slug: "lovable",
    website: "https://lovable.dev",
    one_liner: "AI app builder that turns prompts into full web apps.",
    description:
      "Lovable is an AI-powered app builder that generates full-stack web applications from natural-language prompts.",
    founded_year: 2023,
    hq_city: "Stockholm",
    hq_country: "Sweden",
    stage: "series_a",
    employee_range: "11-50",
    categories: ["Dev Tools", "No-Code", "Coding Agents"],
    tags: ["app builder", "vibe coding"],
    is_unicorn: true,
    valuation_usd: 1800000000,
    status: "active",
    linkedin_url: null,
  },
  {
    name: "Bolt (StackBlitz)",
    slug: "bolt-stackblitz",
    website: "https://bolt.new",
    one_liner: "AI-powered in-browser full-stack app builder.",
    description:
      "StackBlitz builds Bolt.new, an AI tool that generates and runs full-stack web applications directly in the browser.",
    founded_year: 2017,
    hq_city: "San Francisco",
    hq_country: "USA",
    stage: "series_b",
    employee_range: "51-200",
    categories: ["Dev Tools", "No-Code"],
    tags: ["browser IDE", "app generation"],
    is_unicorn: false,
    valuation_usd: 700000000,
    status: "active",
    linkedin_url: "https://linkedin.com/company/stackblitz",
  },
  {
    name: "Vercel",
    slug: "vercel",
    website: "https://vercel.com",
    one_liner: "Frontend cloud platform with AI-assisted development tools (v0).",
    description:
      "Vercel provides a frontend cloud platform for deploying web applications, alongside the AI-powered UI generation tool v0.",
    founded_year: 2015,
    hq_city: "San Francisco",
    hq_country: "USA",
    stage: "series_d_plus",
    employee_range: "501-1000",
    categories: ["Dev Tools", "Infra", "Coding Agents"],
    tags: ["v0", "hosting", "Next.js"],
    is_unicorn: true,
    valuation_usd: 9300000000,
    status: "active",
    linkedin_url: "https://linkedin.com/company/vercel",
  },
  {
    name: "Fireworks AI",
    slug: "fireworks-ai",
    website: "https://fireworks.ai",
    one_liner: "Fast inference platform for open-source generative AI models.",
    description:
      "Fireworks AI provides optimized, low-latency inference infrastructure for serving open-source generative AI models at scale.",
    founded_year: 2022,
    hq_city: "Redwood City",
    hq_country: "USA",
    stage: "series_b",
    employee_range: "51-200",
    categories: ["Infra", "Inference", "Compute"],
    tags: ["inference platform"],
    is_unicorn: true,
    valuation_usd: 4000000000,
    status: "active",
    linkedin_url: "https://linkedin.com/company/fireworks-ai",
  },
  {
    name: "Baseten",
    slug: "baseten",
    website: "https://baseten.co",
    one_liner: "Infrastructure platform for deploying ML models in production.",
    description:
      "Baseten provides model deployment and inference infrastructure that helps teams ship custom ML models to production.",
    founded_year: 2019,
    hq_city: "San Francisco",
    hq_country: "USA",
    stage: "series_b",
    employee_range: "51-200",
    categories: ["Infra", "MLOps", "Inference"],
    tags: ["model deployment"],
    is_unicorn: false,
    valuation_usd: 825000000,
    status: "active",
    linkedin_url: "https://linkedin.com/company/baseten",
  },
  {
    name: "Cerebras Systems",
    slug: "cerebras-systems",
    website: "https://cerebras.ai",
    one_liner: "Wafer-scale AI chips for training and inference.",
    description:
      "Cerebras designs wafer-scale processors purpose-built for AI training and inference, aiming to outperform traditional GPU clusters.",
    founded_year: 2016,
    hq_city: "Sunnyvale",
    hq_country: "USA",
    stage: "series_d_plus",
    employee_range: "501-1000",
    categories: ["Hardware", "Chips", "Compute"],
    tags: ["wafer-scale", "silicon"],
    is_unicorn: true,
    valuation_usd: 8000000000,
    status: "active",
    linkedin_url: "https://linkedin.com/company/cerebras-systems",
  },
  {
    name: "SambaNova Systems",
    slug: "sambanova-systems",
    website: "https://sambanova.ai",
    one_liner: "Full-stack AI platform with custom chips.",
    description:
      "SambaNova builds a full-stack AI platform, including custom silicon (RDU chips), for enterprise and government AI deployment.",
    founded_year: 2017,
    hq_city: "Palo Alto",
    hq_country: "USA",
    stage: "series_d_plus",
    employee_range: "501-1000",
    categories: ["Hardware", "Chips", "Enterprise AI"],
    tags: ["RDU", "full-stack AI"],
    is_unicorn: true,
    valuation_usd: 5100000000,
    status: "active",
    linkedin_url: "https://linkedin.com/company/sambanova-systems",
  },
  {
    name: "Imbue",
    slug: "imbue",
    website: "https://imbue.com",
    one_liner: "Research lab building reasoning-focused AI agents.",
    description:
      "Imbue conducts foundational AI research aimed at building agents that can robustly reason and code, training its own models in-house.",
    founded_year: 2021,
    hq_city: "San Francisco",
    hq_country: "USA",
    stage: "series_b",
    employee_range: "51-200",
    categories: ["Agents", "Foundation Models", "AI Safety"],
    tags: ["reasoning", "research lab"],
    is_unicorn: true,
    valuation_usd: 1000000000,
    status: "active",
    linkedin_url: "https://linkedin.com/company/imbue-ai",
  },
  {
    name: "Writer",
    slug: "writer",
    website: "https://writer.com",
    one_liner: "Full-stack generative AI platform for enterprises.",
    description:
      "Writer provides a full-stack generative AI platform, including proprietary models and applications, for enterprise content and workflow automation.",
    founded_year: 2020,
    hq_city: "San Francisco",
    hq_country: "USA",
    stage: "series_c",
    employee_range: "201-500",
    categories: ["Enterprise AI", "Generative Text"],
    tags: ["enterprise LLM", "content generation"],
    is_unicorn: true,
    valuation_usd: 1900000000,
    status: "active",
    linkedin_url: "https://linkedin.com/company/get-writer",
  },
  {
    name: "Jasper AI",
    slug: "jasper-ai",
    website: "https://jasper.ai",
    one_liner: "AI content generation platform for marketing teams.",
    description:
      "Jasper provides generative AI tools focused on marketing content creation, brand voice, and campaign workflows.",
    founded_year: 2021,
    hq_city: "Austin",
    hq_country: "USA",
    stage: "series_a",
    employee_range: "201-500",
    categories: ["Marketing Tech", "Generative Text"],
    tags: ["marketing AI", "content"],
    is_unicorn: true,
    valuation_usd: 1500000000,
    status: "active",
    linkedin_url: "https://linkedin.com/company/jasperai",
  },
];
