export interface SeedFundingRound {
  company_slug: string;
  round_type:
    | "pre_seed"
    | "seed"
    | "series_a"
    | "series_b"
    | "series_c"
    | "series_d"
    | "series_e_plus"
    | "bridge"
    | "convertible_note"
    | "grant"
    | "ipo"
    | "acquisition";
  amount_usd: number | null;
  announced_date: string; // YYYY-MM-DD
  valuation_usd: number | null;
  is_valuation_disclosed: boolean;
  lead_investor_slug: string | null;
  participant_investor_slugs: string[]; // excluding lead, lead is added automatically
  notes?: string;
}

export const seedFundingRounds: SeedFundingRound[] = [
  {
    company_slug: "openai",
    round_type: "series_e_plus",
    amount_usd: 40000000000,
    announced_date: "2025-03-31",
    valuation_usd: 157000000000,
    is_valuation_disclosed: true,
    lead_investor_slug: "thrive-capital",
    participant_investor_slugs: ["microsoft"],
    notes: "Large primary round led by Thrive Capital with participation from Microsoft.",
  },
  {
    company_slug: "openai",
    round_type: "series_e_plus",
    amount_usd: 6600000000,
    announced_date: "2024-10-02",
    valuation_usd: 157000000000,
    is_valuation_disclosed: true,
    lead_investor_slug: "thrive-capital",
    participant_investor_slugs: ["microsoft", "khosla-ventures"],
  },
  {
    company_slug: "anthropic",
    round_type: "series_e_plus",
    amount_usd: 3500000000,
    announced_date: "2025-03-03",
    valuation_usd: 61500000000,
    is_valuation_disclosed: true,
    lead_investor_slug: "lightspeed-venture-partners",
    participant_investor_slugs: ["general-catalyst", "coatue-management"],
  },
  {
    company_slug: "anthropic",
    round_type: "series_d",
    amount_usd: 4000000000,
    announced_date: "2024-01-22",
    valuation_usd: 18400000000,
    is_valuation_disclosed: true,
    lead_investor_slug: "amazon",
    participant_investor_slugs: [],
  },
  {
    company_slug: "mistral-ai",
    round_type: "series_b",
    amount_usd: 645000000,
    announced_date: "2024-06-11",
    valuation_usd: 6200000000,
    is_valuation_disclosed: true,
    lead_investor_slug: "general-catalyst",
    participant_investor_slugs: ["andreessen-horowitz", "nvidia"],
  },
  {
    company_slug: "cohere",
    round_type: "series_d",
    amount_usd: 500000000,
    announced_date: "2024-07-22",
    valuation_usd: 5500000000,
    is_valuation_disclosed: true,
    lead_investor_slug: "salesforce-ventures",
    participant_investor_slugs: ["nvidia", "amazon"],
  },
  {
    company_slug: "perplexity",
    round_type: "series_e_plus",
    amount_usd: 500000000,
    announced_date: "2024-12-09",
    valuation_usd: 9000000000,
    is_valuation_disclosed: true,
    lead_investor_slug: "iconiq-growth",
    participant_investor_slugs: ["accel"],
  },
  {
    company_slug: "perplexity",
    round_type: "series_e_plus",
    amount_usd: 200000000,
    announced_date: "2025-07-15",
    valuation_usd: 18000000000,
    is_valuation_disclosed: true,
    lead_investor_slug: "accel",
    participant_investor_slugs: [],
  },
  {
    company_slug: "hugging-face",
    round_type: "series_d",
    amount_usd: 235000000,
    announced_date: "2023-08-24",
    valuation_usd: 4500000000,
    is_valuation_disclosed: true,
    lead_investor_slug: "salesforce-ventures",
    participant_investor_slugs: ["nvidia", "amazon", "microsoft"],
  },
  {
    company_slug: "scale-ai",
    round_type: "series_e_plus",
    amount_usd: 1000000000,
    announced_date: "2024-05-21",
    valuation_usd: 13800000000,
    is_valuation_disclosed: true,
    lead_investor_slug: "accel",
    participant_investor_slugs: ["amazon", "nvidia"],
  },
  {
    company_slug: "together-ai",
    round_type: "series_b",
    amount_usd: 106000000,
    announced_date: "2024-03-12",
    valuation_usd: 1250000000,
    is_valuation_disclosed: true,
    lead_investor_slug: "general-catalyst",
    participant_investor_slugs: ["khosla-ventures", "nvidia"],
  },
  {
    company_slug: "groq",
    round_type: "series_d",
    amount_usd: 640000000,
    announced_date: "2024-08-05",
    valuation_usd: 2800000000,
    is_valuation_disclosed: true,
    lead_investor_slug: "bond-capital",
    participant_investor_slugs: ["khosla-ventures"],
  },
  {
    company_slug: "runway",
    round_type: "series_d",
    amount_usd: 308000000,
    announced_date: "2024-04-03",
    valuation_usd: 3000000000,
    is_valuation_disclosed: true,
    lead_investor_slug: "general-catalyst",
    participant_investor_slugs: ["nvidia"],
  },
  {
    company_slug: "character-ai",
    round_type: "series_a",
    amount_usd: 150000000,
    announced_date: "2023-03-23",
    valuation_usd: 1000000000,
    is_valuation_disclosed: true,
    lead_investor_slug: "andreessen-horowitz",
    participant_investor_slugs: [],
  },
  {
    company_slug: "glean",
    round_type: "series_e_plus",
    amount_usd: 260000000,
    announced_date: "2025-06-25",
    valuation_usd: 7200000000,
    is_valuation_disclosed: true,
    lead_investor_slug: "general-catalyst",
    participant_investor_slugs: ["iconiq-growth"],
  },
  {
    company_slug: "harvey",
    round_type: "series_d",
    amount_usd: 300000000,
    announced_date: "2025-02-18",
    valuation_usd: 5000000000,
    is_valuation_disclosed: true,
    lead_investor_slug: "sequoia-capital",
    participant_investor_slugs: ["thrive-capital"],
  },
  {
    company_slug: "sierra",
    round_type: "series_b",
    amount_usd: 350000000,
    announced_date: "2025-06-19",
    valuation_usd: 10000000000,
    is_valuation_disclosed: true,
    lead_investor_slug: "greenoaks-capital",
    participant_investor_slugs: ["thrive-capital", "iconiq-growth"],
  },
  {
    company_slug: "cursor",
    round_type: "series_c",
    amount_usd: 900000000,
    announced_date: "2025-06-05",
    valuation_usd: 9900000000,
    is_valuation_disclosed: true,
    lead_investor_slug: "thrive-capital",
    participant_investor_slugs: ["accel", "andreessen-horowitz"],
  },
  {
    company_slug: "replit",
    round_type: "series_b",
    amount_usd: 97400000,
    announced_date: "2023-04-12",
    valuation_usd: 1160000000,
    is_valuation_disclosed: true,
    lead_investor_slug: "andreessen-horowitz",
    participant_investor_slugs: ["khosla-ventures"],
  },
  {
    company_slug: "adept-ai",
    round_type: "series_b",
    amount_usd: 350000000,
    announced_date: "2023-03-14",
    valuation_usd: 1000000000,
    is_valuation_disclosed: true,
    lead_investor_slug: "general-catalyst",
    participant_investor_slugs: ["khosla-ventures", "nvidia"],
  },
  {
    company_slug: "inflection-ai",
    round_type: "series_b",
    amount_usd: 1300000000,
    announced_date: "2023-06-29",
    valuation_usd: 4000000000,
    is_valuation_disclosed: true,
    lead_investor_slug: "microsoft",
    participant_investor_slugs: ["nvidia"],
  },
  {
    company_slug: "stability-ai",
    round_type: "series_c",
    amount_usd: 100000000,
    announced_date: "2023-10-05",
    valuation_usd: 1000000000,
    is_valuation_disclosed: false,
    lead_investor_slug: null,
    participant_investor_slugs: [],
  },
  {
    company_slug: "elevenlabs",
    round_type: "series_c",
    amount_usd: 180000000,
    announced_date: "2025-01-30",
    valuation_usd: 3300000000,
    is_valuation_disclosed: true,
    lead_investor_slug: "andreessen-horowitz",
    participant_investor_slugs: ["accel"],
  },
  {
    company_slug: "synthesia",
    round_type: "series_d",
    amount_usd: 180000000,
    announced_date: "2024-04-11",
    valuation_usd: 2100000000,
    is_valuation_disclosed: true,
    lead_investor_slug: "nvidia",
    participant_investor_slugs: ["accel", "general-catalyst"],
  },
  {
    company_slug: "pika",
    round_type: "series_b",
    amount_usd: 80000000,
    announced_date: "2024-06-18",
    valuation_usd: 470000000,
    is_valuation_disclosed: true,
    lead_investor_slug: "lightspeed-venture-partners",
    participant_investor_slugs: [],
  },
  {
    company_slug: "suno",
    round_type: "series_b",
    amount_usd: 125000000,
    announced_date: "2025-05-21",
    valuation_usd: 2450000000,
    is_valuation_disclosed: true,
    lead_investor_slug: "lightspeed-venture-partners",
    participant_investor_slugs: ["founders-fund"],
  },
  {
    company_slug: "pinecone",
    round_type: "series_b",
    amount_usd: 100000000,
    announced_date: "2023-04-24",
    valuation_usd: 750000000,
    is_valuation_disclosed: true,
    lead_investor_slug: "andreessen-horowitz",
    participant_investor_slugs: ["iconiq-growth"],
  },
  {
    company_slug: "weights-and-biases",
    round_type: "series_c",
    amount_usd: 200000000,
    announced_date: "2021-10-12",
    valuation_usd: 1250000000,
    is_valuation_disclosed: true,
    lead_investor_slug: "coatue-management",
    participant_investor_slugs: ["index-ventures"],
  },
  {
    company_slug: "langchain",
    round_type: "series_a",
    amount_usd: 125000000,
    announced_date: "2025-02-04",
    valuation_usd: 1250000000,
    is_valuation_disclosed: true,
    lead_investor_slug: "andreessen-horowitz",
    participant_investor_slugs: ["sequoia-capital"],
  },
  {
    company_slug: "magic-ai",
    round_type: "series_b",
    amount_usd: 320000000,
    announced_date: "2024-08-01",
    valuation_usd: 1500000000,
    is_valuation_disclosed: true,
    lead_investor_slug: "founders-fund",
    participant_investor_slugs: ["nvidia"],
  },
  {
    company_slug: "codeium",
    round_type: "series_c",
    amount_usd: 150000000,
    announced_date: "2024-08-29",
    valuation_usd: 1250000000,
    is_valuation_disclosed: true,
    lead_investor_slug: "general-catalyst",
    participant_investor_slugs: ["khosla-ventures"],
  },
  {
    company_slug: "mercor",
    round_type: "series_b",
    amount_usd: 100000000,
    announced_date: "2025-02-20",
    valuation_usd: 2000000000,
    is_valuation_disclosed: true,
    lead_investor_slug: "general-catalyst",
    participant_investor_slugs: [],
  },
  {
    company_slug: "decagon",
    round_type: "series_c",
    amount_usd: 131000000,
    announced_date: "2025-05-13",
    valuation_usd: 1500000000,
    is_valuation_disclosed: true,
    lead_investor_slug: "accel",
    participant_investor_slugs: ["bond-capital"],
  },
  {
    company_slug: "physical-intelligence",
    round_type: "series_a",
    amount_usd: 400000000,
    announced_date: "2024-11-04",
    valuation_usd: 2400000000,
    is_valuation_disclosed: true,
    lead_investor_slug: "thrive-capital",
    participant_investor_slugs: ["amazon", "nvidia"],
  },
  {
    company_slug: "figure-ai",
    round_type: "series_b",
    amount_usd: 675000000,
    announced_date: "2024-02-29",
    valuation_usd: 2600000000,
    is_valuation_disclosed: true,
    lead_investor_slug: "microsoft",
    participant_investor_slugs: ["nvidia", "amazon"],
  },
  {
    company_slug: "skild-ai",
    round_type: "series_a",
    amount_usd: 300000000,
    announced_date: "2024-07-10",
    valuation_usd: 1500000000,
    is_valuation_disclosed: true,
    lead_investor_slug: "lightspeed-venture-partners",
    participant_investor_slugs: ["coatue-management"],
  },
  {
    company_slug: "world-labs",
    round_type: "seed",
    amount_usd: 230000000,
    announced_date: "2024-09-10",
    valuation_usd: 1000000000,
    is_valuation_disclosed: true,
    lead_investor_slug: "andreessen-horowitz",
    participant_investor_slugs: ["radical-ventures", "nvidia"],
  },
  {
    company_slug: "safe-superintelligence",
    round_type: "series_a",
    amount_usd: 1000000000,
    announced_date: "2024-09-04",
    valuation_usd: 5000000000,
    is_valuation_disclosed: true,
    lead_investor_slug: "andreessen-horowitz",
    participant_investor_slugs: ["sequoia-capital", "founders-fund"],
  },
  {
    company_slug: "thinking-machines-lab",
    round_type: "seed",
    amount_usd: 2000000000,
    announced_date: "2025-07-15",
    valuation_usd: 12000000000,
    is_valuation_disclosed: true,
    lead_investor_slug: "andreessen-horowitz",
    participant_investor_slugs: ["accel", "thrive-capital"],
  },
  {
    company_slug: "lovable",
    round_type: "series_a",
    amount_usd: 200000000,
    announced_date: "2025-07-08",
    valuation_usd: 1800000000,
    is_valuation_disclosed: true,
    lead_investor_slug: "accel",
    participant_investor_slugs: [],
  },
  {
    company_slug: "fireworks-ai",
    round_type: "series_c",
    amount_usd: 250000000,
    announced_date: "2025-04-30",
    valuation_usd: 4000000000,
    is_valuation_disclosed: true,
    lead_investor_slug: "sequoia-capital",
    participant_investor_slugs: ["index-ventures"],
  },
  {
    company_slug: "baseten",
    round_type: "series_c",
    amount_usd: 150000000,
    announced_date: "2025-05-20",
    valuation_usd: 825000000,
    is_valuation_disclosed: true,
    lead_investor_slug: "iconiq-growth",
    participant_investor_slugs: ["sequoia-capital", "index-ventures"],
  },
  {
    company_slug: "cerebras-systems",
    round_type: "series_e_plus",
    amount_usd: 250000000,
    announced_date: "2024-08-09",
    valuation_usd: 8000000000,
    is_valuation_disclosed: true,
    lead_investor_slug: "accel",
    participant_investor_slugs: [],
  },
  {
    company_slug: "imbue",
    round_type: "series_b",
    amount_usd: 200000000,
    announced_date: "2023-09-06",
    valuation_usd: 1000000000,
    is_valuation_disclosed: true,
    lead_investor_slug: "founders-fund",
    participant_investor_slugs: ["nvidia"],
  },
  {
    company_slug: "writer",
    round_type: "series_c",
    amount_usd: 200000000,
    announced_date: "2024-11-12",
    valuation_usd: 1900000000,
    is_valuation_disclosed: true,
    lead_investor_slug: "iconiq-growth",
    participant_investor_slugs: ["accel"],
  },
  {
    company_slug: "jasper-ai",
    round_type: "series_a",
    amount_usd: 125000000,
    announced_date: "2022-10-18",
    valuation_usd: 1500000000,
    is_valuation_disclosed: true,
    lead_investor_slug: "iconiq-growth",
    participant_investor_slugs: [],
  },
];
